/* eslint-disable @typescript-eslint/no-explicit-any */
// Server-side invitation email delivery via Brevo (through the Lovable
// connector gateway). Uses a secure token generated by the
// `create_invitation` RPC; the email links to `/join/{token}` where the
// `accept_invitation` RPC atomically joins the user and flips the row
// from `pending` → `accepted`. Expired / rejected / already-accepted
// invitations are rejected by the RPC.
import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

const BREVO_ENDPOINT = "https://connector-gateway.lovable.dev/brevo/v3/smtp/email";
const BREVO_DOMAINS_ENDPOINT = "https://connector-gateway.lovable.dev/brevo/v3/senders/domains";

type SendResult =
  | { sent: true; via?: "brevo" }
  | { sent: false; reason: "not_configured" | "suppressed" | "failed"; detail?: string };

const sendSchema = z.object({
  email: z.string().email(),
  token: z.string().min(10),
  organizationId: z.string().uuid(),
  inviterName: z.string().optional(),
});

// Kept for backward-compat with the Members page which imports
// `sendAuthInvitation` dynamically. Sends the branded invite email via
// Brevo — the token-based `/join/{token}` accept flow handles both new
// signups and existing users, so no Supabase Auth invite is required.
export const sendAuthInvitation = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((v: unknown) => sendSchema.parse(v))
  .handler(async ({ data, context }): Promise<SendResult> => {
    return await sendInvite(data, context);
  });

export const sendInvitationEmail = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((v: unknown) => sendSchema.parse(v))
  .handler(async ({ data, context }): Promise<SendResult> => {
    return await sendInvite(data, context);
  });

async function sendInvite(
  data: z.infer<typeof sendSchema>,
  context: { supabase: any; userId: string },
): Promise<SendResult> {
  // Defense-in-depth: caller must be owner/admin of the org.
  const { data: membership } = await context.supabase
    .from("organization_members")
    .select("role")
    .eq("organization_id", data.organizationId)
    .eq("user_id", context.userId)
    .maybeSingle();
  if (!membership || !["owner", "admin"].includes(membership.role as string)) {
    return { sent: false, reason: "failed", detail: "not_admin" };
  }

  const { data: org } = await context.supabase
    .from("organizations")
    .select("name")
    .eq("id", data.organizationId)
    .maybeSingle();
  const orgName = org?.name ?? "your organization";
  const inviter = data.inviterName ?? "A teammate";

  const origin =
    process.env.APP_URL ||
    process.env.PUBLIC_APP_URL ||
    "https://snuggle-sparkle-net.lovable.app";
  const inviteUrl = `${origin.replace(/\/$/, "")}/join/${data.token}`;

  return await sendViaBrevo({
    to: data.email,
    subject: `You're invited to join ${orgName}`,
    html: renderInviteHtml({ orgName, inviteUrl, inviter }),
  });
}

function renderInviteHtml(opts: { orgName: string; inviteUrl: string; inviter: string }) {
  const { orgName, inviteUrl, inviter } = opts;
  return `<!doctype html><html><body style="font-family:Inter,Arial,sans-serif;background:#fff;color:#0f172a;padding:24px">
    <div style="max-width:560px;margin:0 auto;padding:32px 28px">
      <h1 style="font-size:22px;margin:0 0 12px">You've been invited to ${escapeHtml(orgName)}</h1>
      <p style="font-size:15px;line-height:22px;margin:0 0 16px">
        ${escapeHtml(inviter)} invited you to collaborate in <strong>${escapeHtml(orgName)}</strong> on Multi-tenant SaaS.
      </p>
      <p style="margin:24px 0">
        <a href="${inviteUrl}" style="display:inline-block;background:#0f172a;color:#fff;text-decoration:none;padding:12px 20px;border-radius:8px;font-weight:600;font-size:14px">Accept invitation</a>
      </p>
      <p style="font-size:15px;line-height:22px;margin:0 0 16px">Or open this link in your browser:<br/>
        <a href="${inviteUrl}" style="color:#2563eb;word-break:break-all">${inviteUrl}</a>
      </p>
      <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0"/>
      <p style="font-size:12px;color:#64748b;margin:0 0 6px">This invitation expires in 14 days.</p>
      <p style="font-size:12px;color:#64748b;margin:0">If you weren't expecting this email, you can safely ignore it.</p>
    </div>
  </body></html>`;
}

function escapeHtml(s: string) {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
}

function parseFrom(): { name: string; email: string } | null {
  const raw = process.env.BREVO_FROM_EMAIL;
  if (!raw) return null;
  // Accept "Name <email@x>" or plain "email@x".
  const m = raw.match(/^\s*(?:"?([^"<]+?)"?\s*)?<([^>]+)>\s*$/);
  if (m) return { name: (m[1] || process.env.BREVO_FROM_NAME || "Multi-tenant SaaS").trim(), email: m[2].trim() };
  return { name: process.env.BREVO_FROM_NAME || "Multi-tenant SaaS", email: raw.trim() };
}

async function sendViaBrevo(opts: {
  to: string;
  subject: string;
  html: string;
}): Promise<SendResult> {
  const lovableKey = process.env.LOVABLE_API_KEY;
  const brevoKey = process.env.BREVO_API_KEY;
  if (!lovableKey || !brevoKey) {
    return { sent: false, reason: "not_configured", detail: "Brevo connector not linked" };
  }
  const sender = parseFrom();
  if (!sender) {
    return {
      sent: false,
      reason: "not_configured",
      detail: "BREVO_FROM_EMAIL is not set. Set it to a verified Brevo sender.",
    };
  }
  try {
    const res = await fetch(BREVO_ENDPOINT, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
        Authorization: `Bearer ${lovableKey}`,
        "X-Connection-Api-Key": brevoKey,
      },
      body: JSON.stringify({
        sender,
        to: [{ email: opts.to }],
        subject: opts.subject,
        htmlContent: opts.html,
      }),
    });
    if (!res.ok) {
      const body = await res.text();
      console.error(`[brevo] send failed [${res.status}]: ${body}`);
      return { sent: false, reason: "failed", detail: `${res.status}: ${body.slice(0, 300)}` };
    }
    return { sent: true, via: "brevo" };
  } catch (err: any) {
    return { sent: false, reason: "failed", detail: err?.message };
  }
}

// Status probe used by Members + Email Settings pages.
export const getInvitationEmailStatus = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async () => {
    const hasLovableKey = !!process.env.LOVABLE_API_KEY;
    const hasBrevoKey = !!process.env.BREVO_API_KEY;
    const hasFrom = !!process.env.BREVO_FROM_EMAIL;
    return {
      configured: hasLovableKey && hasBrevoKey && hasFrom,
      checks: {
        lovableKey: hasLovableKey,
        emailHelper: hasBrevoKey,
        invitationTemplate: hasFrom,
      },
    };
  });

const testSchema = z.object({
  email: z.string().email(),
  organizationName: z.string().min(1).max(200),
  inviterName: z.string().min(1).max(200),
  inviteUrl: z.string().url(),
});

export const sendTestInvitationEmail = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((v: unknown) => testSchema.parse(v))
  .handler(async ({ data }): Promise<SendResult> => {
    return await sendViaBrevo({
      to: data.email,
      subject: `You're invited to join ${data.organizationName}`,
      html: renderInviteHtml({
        orgName: data.organizationName,
        inviteUrl: data.inviteUrl,
        inviter: data.inviterName,
      }),
    });
  });

// Email delivery log listing is not available via the Brevo connector in
// this project — return an empty result so the UI degrades gracefully.
const logsSchema = z.object({
  organizationId: z.string().uuid(),
  limit: z.number().int().min(1).max(200).optional(),
});
export type InvitationEmailLog = {
  timestamp: string;
  recipient: string;
  event_type: string;
  status: string | null;
  message_id: string | null;
};
export type InvitationEmailLogsResult =
  | {
      available: true;
      events: InvitationEmailLog[];
      historyStartsAt: string | null;
      recipientCount: number;
    }
  | { available: false; reason: "not_configured" | "failed"; detail?: string };

export const listInvitationEmailLogs = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((v: unknown) => logsSchema.parse(v))
  .handler(async (): Promise<InvitationEmailLogsResult> => {
    return { available: false, reason: "not_configured", detail: "brevo_logs_unavailable" };
  });

// Config status for the Email Settings page. Reports Brevo key + From
// address, and — if reachable — the list of authenticated sender domains
// in the connected Brevo account.
export type ResendConfigStatus = {
  configured: boolean;
  hasResendKey: boolean;
  hasLovableKey: boolean;
  fromEmail: string;
  fromEmailSource: "env" | "default";
  domains:
    | { available: true; items: { name: string; status: string; region?: string | null }[] }
    | { available: false; reason: string };
};

export const getResendConfigStatus = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async (): Promise<ResendConfigStatus> => {
    const hasLovableKey = !!process.env.LOVABLE_API_KEY;
    const hasBrevoKey = !!process.env.BREVO_API_KEY;
    const fromEmail =
      process.env.BREVO_FROM_EMAIL ?? "(not configured — set BREVO_FROM_EMAIL)";
    const fromEmailSource: "env" | "default" = process.env.BREVO_FROM_EMAIL ? "env" : "default";

    let domains: ResendConfigStatus["domains"] = {
      available: false,
      reason: "brevo_key_missing",
    };
    if (hasLovableKey && hasBrevoKey) {
      try {
        const res = await fetch(BREVO_DOMAINS_ENDPOINT, {
          method: "GET",
          headers: {
            Accept: "application/json",
            Authorization: `Bearer ${process.env.LOVABLE_API_KEY}`,
            "X-Connection-Api-Key": process.env.BREVO_API_KEY!,
          },
        });
        if (res.ok) {
          const body = (await res.json()) as {
            domains?: { domain_name?: string; name?: string; authenticated?: boolean; verified?: boolean }[];
          };
          const items = (body.domains ?? []).map((d) => ({
            name: d.domain_name ?? d.name ?? "",
            status: (d.authenticated ?? d.verified) ? "verified" : "pending",
            region: null,
          }));
          domains = { available: true, items };
        } else {
          const text = await res.text();
          domains = { available: false, reason: `${res.status}: ${text.slice(0, 200)}` };
        }
      } catch (err: any) {
        domains = { available: false, reason: err?.message ?? "network_error" };
      }
    }

    return {
      configured: hasLovableKey && hasBrevoKey && !!process.env.BREVO_FROM_EMAIL,
      hasResendKey: hasBrevoKey,
      hasLovableKey,
      fromEmail,
      fromEmailSource,
      domains,
    };
  });
