/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams.$teamId'
import { Route as AuthenticatedOrganizationsSlugRouteImport } from './routes/_authenticated/organizations.$slug'
import { Route as AuthenticatedOrganizationsSlugSettingsRouteImport } from './routes/_authenticated/organizations.$slug.settings'
import { Route as AuthenticatedOrganizationsSlugMembersRouteImport } from './routes/_authenticated/organizations.$slug.members'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedTeamsRoute,
  } as any)
const AuthenticatedOrganizationsSlugRoute =
  AuthenticatedOrganizationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedOrganizationsRoute,
  } as any)
const AuthenticatedOrganizationsSlugSettingsRoute =
  AuthenticatedOrganizationsSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrganizationsSlugRoute,
  } as any)
const AuthenticatedOrganizationsSlugMembersRoute =
  AuthenticatedOrganizationsSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedOrganizationsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/join/$token': typeof JoinTokenRoute
  '/organizations/$slug': typeof AuthenticatedOrganizationsSlugRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/organizations/$slug/members': typeof AuthenticatedOrganizationsSlugMembersRoute
  '/organizations/$slug/settings': typeof AuthenticatedOrganizationsSlugSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/join/$token': typeof JoinTokenRoute
  '/organizations/$slug': typeof AuthenticatedOrganizationsSlugRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/organizations/$slug/members': typeof AuthenticatedOrganizationsSlugMembersRoute
  '/organizations/$slug/settings': typeof AuthenticatedOrganizationsSlugSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/join/$token': typeof JoinTokenRoute
  '/_authenticated/organizations/$slug': typeof AuthenticatedOrganizationsSlugRouteWithChildren
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/_authenticated/organizations/$slug/members': typeof AuthenticatedOrganizationsSlugMembersRoute
  '/_authenticated/organizations/$slug/settings': typeof AuthenticatedOrganizationsSlugSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/departments'
    | '/invitations'
    | '/organizations'
    | '/profile'
    | '/teams'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/join/$token'
    | '/organizations/$slug'
    | '/teams/$teamId'
    | '/organizations/$slug/members'
    | '/organizations/$slug/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/departments'
    | '/invitations'
    | '/organizations'
    | '/profile'
    | '/teams'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/join/$token'
    | '/organizations/$slug'
    | '/teams/$teamId'
    | '/organizations/$slug/members'
    | '/organizations/$slug/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/invitations'
    | '/_authenticated/organizations'
    | '/_authenticated/profile'
    | '/_authenticated/teams'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/join/$token'
    | '/_authenticated/organizations/$slug'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/organizations/$slug/members'
    | '/_authenticated/organizations/$slug/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/organizations/$slug': {
      id: '/_authenticated/organizations/$slug'
      path: '/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof AuthenticatedOrganizationsSlugRouteImport
      parentRoute: typeof AuthenticatedOrganizationsRoute
    }
    '/_authenticated/organizations/$slug/settings': {
      id: '/_authenticated/organizations/$slug/settings'
      path: '/settings'
      fullPath: '/organizations/$slug/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationsSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedOrganizationsSlugRoute
    }
    '/_authenticated/organizations/$slug/members': {
      id: '/_authenticated/organizations/$slug/members'
      path: '/members'
      fullPath: '/organizations/$slug/members'
      preLoaderRoute: typeof AuthenticatedOrganizationsSlugMembersRouteImport
      parentRoute: typeof AuthenticatedOrganizationsSlugRoute
    }
  }
}

interface AuthenticatedOrganizationsSlugRouteChildren {
  AuthenticatedOrganizationsSlugMembersRoute: typeof AuthenticatedOrganizationsSlugMembersRoute
  AuthenticatedOrganizationsSlugSettingsRoute: typeof AuthenticatedOrganizationsSlugSettingsRoute
}

const AuthenticatedOrganizationsSlugRouteChildren: AuthenticatedOrganizationsSlugRouteChildren =
  {
    AuthenticatedOrganizationsSlugMembersRoute:
      AuthenticatedOrganizationsSlugMembersRoute,
    AuthenticatedOrganizationsSlugSettingsRoute:
      AuthenticatedOrganizationsSlugSettingsRoute,
  }

const AuthenticatedOrganizationsSlugRouteWithChildren =
  AuthenticatedOrganizationsSlugRoute._addFileChildren(
    AuthenticatedOrganizationsSlugRouteChildren,
  )

interface AuthenticatedOrganizationsRouteChildren {
  AuthenticatedOrganizationsSlugRoute: typeof AuthenticatedOrganizationsSlugRouteWithChildren
}

const AuthenticatedOrganizationsRouteChildren: AuthenticatedOrganizationsRouteChildren =
  {
    AuthenticatedOrganizationsSlugRoute:
      AuthenticatedOrganizationsSlugRouteWithChildren,
  }

const AuthenticatedOrganizationsRouteWithChildren =
  AuthenticatedOrganizationsRoute._addFileChildren(
    AuthenticatedOrganizationsRouteChildren,
  )

interface AuthenticatedTeamsRouteChildren {
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
}

const AuthenticatedTeamsRouteChildren: AuthenticatedTeamsRouteChildren = {
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
}

const AuthenticatedTeamsRouteWithChildren =
  AuthenticatedTeamsRoute._addFileChildren(AuthenticatedTeamsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
